"""
Client Views: CLI functions for client management by the sales team.
"""
from rich.console import Console
from rich.prompt import Prompt, Confirm
from rich.table import Table
import re # Added for validation helpers if necessary
from datetime import datetime

# Local import of check_permission to respect the minimum dependency principle
from app.models import Employee 
from app.controllers.client_controller import list_clients, create_client, update_client
from app.controllers.utils import is_valid_email, is_valid_phone

# To display the list of sales staff during reassignment
from app.controllers.employee_controller import list_employees 

console = Console()


# --- Display Functions ---

def display_client_table(clients: list, title: str):
    """Utility function to display clients in a Rich Table."""
    if not clients:
        # Translated: No client found for the 'title' display.
        console.print(f"[bold yellow]INFO:[/bold yellow] No client found for the '{title}' display.")
        return

    table = Table(title=title, show_header=True, header_style="bold cyan")
    table.add_column("ID", style="dim", width=5)
    table.add_column("Full Name", style="bold", min_width=20)
    table.add_column("Company", min_width=20)
    table.add_column("Email", min_width=30)
    table.add_column("sales Contact (ID)", style="yellow", min_width=20)
    table.add_column("Last Update", style="dim", min_width=15)
    
    for client in clients:
        sales_name = client.sales_contact.full_name if client.sales_contact else "N/A"
        
        table.add_row(
            str(client.id),
            client.full_name,
            client.company_name or "N/A",
            client.email,
            f"{sales_name} ({client.sales_contact_id})",
            client.last_update.strftime("%Y-%m-%d %H:%M") if client.last_update else "N/A"
        )
    console.print(table)


# --- CLI Functions ---

def create_client_cli(session, current_employee: Employee) -> None:
    """
    CLI interface to gather data and call the pure controller function to create a new Client.
    Requires 'Commercial' or 'Gestion' permission.
    """
    # ... (Permission check, unchanged)

    # Translated: -- CREATE NEW CLIENT --
    console.print("\n[bold green]-- CREATE NEW CLIENT --[/bold green]")

    while True:
        # 1. Gather data
        full_name = Prompt.ask("Client Full Name").strip()
        company_name = Prompt.ask("Company Name").strip()
        email = Prompt.ask("Client Email").strip()
        phone = Prompt.ask("Phone Number").strip()

        # 2. Call controller
        try:
            new_client = create_client(
                session,
                current_employee,
                full_name=full_name,
                email=email,
                phone=phone,
                company_name=company_name
            )

            if new_client:
                # Translated: SUCCESS: Client '...' created with ID ... and assigned to you.
                console.print(f"\n[bold green]SUCCESS:[/bold green] Client '{new_client.full_name}' created with ID {new_client.id} and assigned to you.")
                break
            # The controller handles errors and displays an ERROR message, so no 'else' here
            
        except PermissionError as e:
            # Display the permission error generated by the controller
            console.print(f"\n[bold red]ERROR:[/bold red] {e}")
            break
        except Exception as e:
            # Handle other exceptions not caught by the controller
            # Translated: FATAL ERROR: An unexpected error occurred:
            console.print(f"\n[bold red]FATAL ERROR:[/bold red] An unexpected error occurred: {e}")
            break


def list_clients_cli(session, current_employee: Employee):
    """CLI to list clients (with filtering option for 'All Clients' or 'My Clients')."""
    console.print("\n[bold blue]-- LIST CLIENTS --[/bold blue]")

    # Filtering Option RESTORED
    # The user is prompted to choose between viewing All clients or only their own.
    # This relies on the controller allowing Commercial users to see all clients when filter_by_sales_id is None.
    choice = Prompt.ask("Filter clients? [1: All Clients | 2: My Clients]", choices=['1', '2'], default='1')

    filter_id = None
    title = "ALL CLIENTS (Read Only)"
    
    if choice == '2':
        # Choice 2: My Clients
        filter_id = current_employee.id
        title = f"MY CLIENTS (Sales ID: {current_employee.id})"
    elif choice == '1':
        # Choice 1: All Clients
        filter_id = None
        title = "ALL CLIENTS (Read Only)"
        
    # Controller Call
    # If filter_id is None (Choice 1), the controller must return all 7 clients.
    clients = list_clients(session, current_employee, filter_by_sales_id=filter_id)

    if clients is not None:
        display_client_table(clients, title)


def update_client_cli(session, current_employee: Employee):
    """CLI to update an existing client."""
    # Translated: -- MODIFY A CLIENT --
    console.print("\n[bold yellow]-- MODIFY A CLIENT --[/bold yellow]")
    
    # 1. ID Input
    while True:
        # Translated: Enter the ID of the client to modify (or 'q' to cancel)
        client_id_str = Prompt.ask("Enter the ID of the client to modify (or 'q' to cancel)").strip()
        if client_id_str.lower() == 'q':
            return
        try:
            client_id = int(client_id_str)
            break
        except ValueError:
            # Translated: Error: ID must be a number.
            console.print("[bold red]Error:[/bold red] ID must be a number.")
            
    # 2. Collect data to update
    updates = {}
    
    # Translated: Leave fields empty to keep current values.
    console.print("[dim]Leave fields empty to keep current values.[/dim]")
    
    # Translated: New full name
    new_name = Prompt.ask("New full name").strip()
    if new_name: updates['full_name'] = new_name
        
    # Translated: New company name
    new_company = Prompt.ask("New company name").strip()
    if new_company: updates['company_name'] = new_company
        
    while True:
        # Translated: New email
        new_email = Prompt.ask("New email").strip()
        if not new_email: break
        if is_valid_email(new_email):
            updates['email'] = new_email
            break
        # Translated: Error: Invalid email format.
        console.print("[bold red]Error:[/bold red] Invalid email format.")
        
    while True:
        # Translated: New phone
        new_phone = Prompt.ask("New phone").strip()
        if not new_phone: break
        if is_valid_phone(new_phone):
            updates['phone'] = new_phone
            break
        # Translated: Error: Invalid phone format.
        console.print("[bold red]Error:[/bold red] Invalid phone format.")
        
    # Change sales contact: Reserved for 'Gestion' team (controller checks permission)
    if current_employee.department == 'Gestion':
        # Translated: Do you want to reassign the Sales Contact?
        if Confirm.ask("Do you want to reassign the Sales Contact?"):
            # Translated: sales
            sales_employees = [e for e in list_employees(session, filter_by_department='sales') if e.department == 'sales']
            
            # Translated: Available Sales Contacts:
            console.print("\n[bold yellow]Available Sales Contacts:[/bold yellow]")
            for emp in sales_employees:
                 console.print(f"  [cyan]{emp.id}[/cyan]: {emp.full_name}")

            # Translated: Enter New sales ID
            new_sales_id_str = Prompt.ask("Enter New sales ID").strip()
            if new_sales_id_str:
                try:
                    # The argument for the controller is 'sales_id'
                    updates['sales_id'] = int(new_sales_id_str) 
                except ValueError:
                    # Translated: Error: Sales ID must be a number. Entry cancelled.
                    console.print("[bold red]Error:[/bold red] Sales ID must be a number. Entry cancelled.")
        
    if not updates:
        # Translated: INFO: No valid data provided for update.
        console.print("[bold yellow]INFO:[/bold yellow] No valid data provided for update.")
        return

    # 3. Controller call
    updated_client = update_client(
        session,
        current_employee,
        client_id,
        **updates
    )
    
    # 4. Display result
    if updated_client:
        # Translated: SUCCESS: Client ID ... updated.
        console.print(f"\n[bold green]SUCCESS:[/bold green] Client ID [cyan]{updated_client.id}[/cyan] updated.")